USE biblioteca_pessoal;
ALTER TABLE Usuario 
    MODIFY COLUMN data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;